[[session]]
name = "responsibid - backend"
path = "~/Projects/Symphosize/responsibid-server"
startup_command = "nvim ."

[[session]]
name = "responsibid - legacy"
path = "~/Projects/Symphosize/responsibid-php"
startup_command = "nvim ."

[[session]]
name = "responsibid - subscriptions"
path = "~/Projects/Symphosize/subscriptions"
startup_command = "nvim ."

[[session]]
name = "responsibid - terraform"
path = "~/Projects/Symphosize/terraform-infra"
startup_command = "nvim ."
